version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-ssl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./sites:/var/www/html
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge 